### ISSUE TITLE
Zfinx ACT

### ISSUE THREAD

**Issue by jjscheel** [riscv-admin/dev-partners#17]
### Technical Group

Unprivileged Spec IC

### ratification-pkg

Zfinx

### Technical Liaison

Tariq Kurd

### Task Category

Arch Tests

### Task Sub Category

- [ ] gcc
- [ ] binutils
- [ ] gdb
- [ ] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike

### Ratification Target

4Q2021

### Statement of Work (SOW)

SOW: [link](https://docs.google.com/document/d/1t--5dfkL7G03zkqijCJxTE6OlYtGDyFAiso0fZmYm7Y/)

**SOW Signoffs:** (delete those not needed)
  - Task group liaison sign-off date: N/A (no longer active)
  - Development partner sign-off date: 9/3/2024 (Anusha)
  - ACT SIG sign-off date (if ACT work): 9/18/2024 (Allen)

### Waiver

- [X] Freeze
- [X] Ratification

### Pull Request Details

- [Arch Test PR #367](https://github.com/riscv-non-isa/riscv-arch-test/pull/367) - merged
- [RISC-V CTG PR #67](https://github.com/riscv-software-src/riscv-ctg/pull/67) - merged
- [RISC-V ISAC PR #72](https://github.com/riscv-software-src/riscv-isac/pull/72) - merged

**Comment by jjscheel** [comment]
Per email from Prasanna on 4/11:
> Zfinix and Zfh : Scheduled a call tomorrow to discuss on the possible solution with respect to sign extension of Zfinix in RV64 (One of the comment provided) - In progress

**Comment by jjscheel** [comment]
Great new, @ptprasanna!  Fingers crossed.

**Comment by jjscheel** [comment]
Updated.  Thank you!

**Comment by anuani21** [comment]
Decoded using rvopcodesdecoder and placed the report in the below link 

 https://gitlab.com/ptprasanna/actreports/-/tree/main/RV64Zfinx?ref_type=heads

**Comment by jjscheel** [comment]
Sounds like we are close!  THANKS.

**Comment by jjscheel** [comment]
@ptprasanna, I would like an update in the issue, by the next meeting on December 12, 2023, please.

**Comment by jjscheel** [comment]
Per @anuani21 in #20:
> Zfinx and Zfh PR for ISAC has been merged.
> https://github.com/riscv-software-src/riscv-isac/pull/72

> 
> Zfinx and Zfh PR from CTG has been waiting for review.
> https://github.com/riscv-software-src/riscv-ctg/pull/67

**Comment by anuani21** [comment]
Zfinx and Zfh PR from CTG has been waiting for review.
    https://github.com/riscv-software-src/riscv-ctg/pull/67

**Comment by anuani21** [comment]
@jjscheel,

Zfinx and Zfh PR for ISAC has been merged.
    https://github.com/riscv-software-src/riscv-isac/pull/72

Zfinx and Zfh PR in arch-test suite has been merged.
    https://github.com/riscv-non-isa/riscv-arch-test/pull/367

Only Zfinx and Zfh PR from CTG has been waiting for approval by Neel.
    https://github.com/riscv-software-src/riscv-ctg/pull/67

**Comment by jjscheel** [comment]
Thanks, @anuani21.  Understand.

@allenjbaum, here is where the work is needed.

**Comment by anuani21** [comment]
@jjscheel,

Zfinx and Zfh PR from CTG still waiting for approval.
https://github.com/riscv-software-src/riscv-ctg/pull/67

**Comment by jjscheel** [comment]
@allenjbaum and @anuani21, I'm inclined to simply mark this as Blocked and leave it for the community to pick up.  It's not fair to IITM to ask them to continue working/watching something that hasn't moved in almost 9 months.

**Comment by jjscheel** [comment]
Thanks, @anuani21.  Please work with Arch Test SIG and @allenjbaum to see if it can be merged.  If they still cannot find people to review it, I propose we simply leave it there until the community becomes active again.

**Comment by anuani21** [comment]
@jjscheel, 

All PR in riscv-ctg,riscv-isac and riscv-arch-test are merged for Zfh and Zfinx.

**Comment by jjscheel** [comment]
@allenjbaum, can you kindly review the work here and signoff on its completion?  A simple approval comment will suffice.

**Comment by jjscheel** [comment]
@allenjbaum, given this comment [Zfh ACT #18](https://github.com/riscv-admin/dev-partners/issues/18#issuecomment-2356679635), I'm going to consider this closed because the PRs were for both Zfh and Zfinx.  Please let me know if that is not correct.
