### ISSUE TITLE
Zfh ACT

### ISSUE THREAD

**Issue by jjscheel** [riscv-admin/dev-partners#18]
### Technical Group

Architecture Test SIG

### ratification-pkg

Zfh

### Technical Liaison

Andrew Waterman

### Task Category

Arch Tests

### Task Sub Category

- [ ] gcc
- [ ] binutils
- [ ] gdb
- [ ] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike

### Ratification Target

4Q2021

### Statement of Work (SOW)

**Component names:**

**Requirements:**
  (prose describing what has to be done and what the end result is)

**Deliverables:**
  - Component 1 and changes expected.
  - Component 2 and changes expected.
  ...

**Acceptance Criteria:**
  - Component 1 and measured result.
  - Component 2 and measured result.
  ...

**Projected timeframe:** (best guess date)

**SOW Signoffs:** (delete those not needed)
  - Task group liaison sign-off date:  N/A
  - Development partner sign-off date: 9/3/2024
  - ACT SIG sign-off date (if ACT work): 9/18/2024

### Waiver

- [X] Freeze
- [X] Ratification

### Pull Request Details

- [Arch Test PR #367](https://github.com/riscv-non-isa/riscv-arch-test/pull/367) - merged
- [riscv-ctg PR #67](https://github.com/riscv-software-src/riscv-ctg/pull/67) - merged
- [riscv-isac PR #72](https://github.com/riscv-software-src/riscv-isac/pull/72) - merged

**Comment by jjscheel** [comment]
Thanks for the update, @ptprasanna.  Good reminder.  I knew this!!!  (But, now we have it written in the issue. :-)

**Comment by anuani21** [comment]
Decoded using rvopcodesdecoder and placed the updated report in the below link:

https://gitlab.com/ptprasanna/actreports/-/tree/main/RV32Zfh?ref_type=heads

**Comment by jjscheel** [comment]
Sounds good.

**Comment by jjscheel** [comment]
Per @anuani21 in #20:
> Zfinx and Zfh PR for ISAC has been merged.
> https://github.com/riscv-software-src/riscv-isac/pull/72

> 
> Zfinx and Zfh PR from CTG has been waiting for review.
> https://github.com/riscv-software-src/riscv-ctg/pull/67

**Comment by jjscheel** [comment]
Per @anuani21 in https://github.com/riscv-admin/dev-partners/issues/20:
> Zfinx and Zfh PR from CTG has been waiting for review.
> https://github.com/riscv-software-src/riscv-ctg/pull/67

**Comment by anuani21** [comment]
@UmerShahidengr, Please review the PR in riscv-ctg  for Zfh and Zfinx extension, https://github.com/riscv-software-src/riscv-ctg/pull/67
and commit.

**Comment by anuani21** [comment]
@jjscheel, 

All PR in riscv-ctg,riscv-isac and riscv-arch-test are merged for Zfh and Zfinx.

**Comment by jjscheel** [comment]
@allenjbaum, can you kindly review the work here and signoff on its completion?  A simple approval comment will suffice.

**Comment by allenjbaum** [comment]
They're all merged, it should be good to go

**Comment by jjscheel** [comment]
Thanks, @allenjbaum!
