### ISSUE TITLE
Vector SAIL

### ISSUE THREAD

**Issue by jjscheel** [riscv-admin/dev-partners#24]
### Technical Group

Vector TG

### ratification-pkg

Vector

### Technical Liaison

Krste

### Task Category

SAIL model

### Task Sub Category

- [ ] gcc
- [ ] binutils
- [ ] gdb
- [ ] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike

### Ratification Target

4Q2021

### Statement of Work (SOW)

SOW: [link](https://docs.google.com/document/d/1XwZm7G0OXdJ98W3InOzieQEuF0rFyJlp/)

**SOW Signoffs:**
  - Task group liaison sign-off date:
  - Development partner sign-off date:
  - SAIL Golden Model sign-off date: 

### Waiver

- [X] Freeze
- [X] Ratification

### Pull Request Details

Original, massive PR was too large for community consumption: https://github.com/riscv/sail-riscv/pull/149

Revised plan was to submit, smaller PRs.  Expect 5-8 PRS instead to split original code.  Here's the current list:
- [PR 1: General V Framework](https://github.com/riscv/sail-riscv/pull/191)
- [PR 2: Load and Store support](https://github.com/riscv/sail-riscv/pull/198)
- [PR 3: Integer/Fixed-point Arithmetic and Mask instructions](https://github.com/riscv/sail-riscv/pull/227)
- [PR 4: Vector floating-point instructions](https://github.com/riscv/sail-riscv/pull/232)
- [PR 5: Vector reduction and mask instructions ](https://github.com/riscv/sail-riscv/pull/259)
- [PR 6: Merging vector extension code from vector-dev to the main branch](https://github.com/riscv/sail-riscv/pull/289)

**Comment by jjscheel** [comment]
Hello, @XinlaiWan!  No action needed here.  I'm just tracking your work for DevPartners.  Please keep working with the SAIL community.  You're doing great work.  Thank you!!!

**Comment by XinlaiWan** [comment]
Got it. Thank you, Jeff!

**Comment by jjscheel** [comment]
Email from Xi:
> RVV Sail Model is waiting for folks reviewing the floating point instructions. We have one more PR and then Sail will be all set.

**Comment by jjscheel** [comment]
@billmcspadden-riscv reported that @XinlaiWan is submitting his 5th and final PR for this item.

Given this, I'm setting the Projected Completion to May 23.

@XinlaiWan, we also discussed the possibility of having your start work on Zvfh and Zvfhmin which was recently ratified.  I'm working the SOW now and hope to have it ready by next meeting.  Please chat with Xi about this.

**Comment by jrtc27** [comment]
When is all the code going through its final review to fix any code style issues that weren't caught because it was going to vector-dev not main and others did not want to impose the same strict standards for that branch?

**Comment by jjscheel** [comment]
Updated primary information with reference to 5th PR.

**Comment by jjscheel** [comment]
Added reference to PR for merge of all code into main.

**Comment by jjscheel** [comment]
@XinlaiWan, any updates here?

**Comment by XinlaiWan** [comment]
The final PR of merging all code into the main branch is being reviewed, and we're waiting for reviewer's suggestions or approvals.

**Comment by jjscheel** [comment]
Thanks, Xinlai!!!
--
Jeff Scheel (he/him/his)
Director of Technical Programs, RISC-V Foundation

**Comment by XinlaiWan** [comment]
Hi Jeff, we'll follow the progress of this, and the development tasks will be assigned to my RIOS colleagues.

**Comment by jrtc27** [comment]
Not complete. https://github.com/riscv/sail-riscv/pull/359 exists, and it likely needs testing to find whatever other issues may remain, since testing can't have been all that thorough if that snuck through.

**Comment by jjscheel** [comment]
Understand @jrtc27.  Thanks for the update.  It's not surprising that in 10+ KLOC there's a bug or two.  I'll keep this open until this first batch of active issues get closed.    

However, the goal for my tracking is to get the function merged into a community for broader exposure and support, not to ensure the last bug has been removed.  Yes, we don't want to compromise code quality, but on the other hand waiting for error-free code is impractical.

**Comment by jjscheel** [comment]
@billmcspadden-riscv, any update on the status of [riscv/sail-riscv#359](https://github.com/riscv/sail-riscv/pull/359)?

**Comment by jjscheel** [comment]
Final issue closed.  Complete.
