### ISSUE TITLE
Bfloat16 gcc,binutils

### ISSUE THREAD

**Issue by Liaoshihua** [riscv-admin/dev-partners#30]
### ratification-pkg
BFloat16

### Technical Liaison
Ken Dockser

### Task Category
Compilers/Toolchain

### Task Sub Category
 

- [x] gcc
- [x] binutils
- [ ] gdb
- [ ] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike
#### SOW Signoffs: (delete those not needed)

- Task group liaison sign-off date:
- Development partner sign-off date:
- Toolchains & Runtimes sign-off date (if gcc, LLVM, binutils, gdb work):
### Waiver
 - [ ] Freeze
 - [ ] Ratification

### Pull Request Details
No response

**Comment by Liaoshihua** [comment]
Hi,@jjscheel 
     
It is PLCT Lab's upstream work, and I hope to be included in the development partner management.
This extension has not been released, although I have already sent RFC patch to upstream

**Comment by jjscheel** [comment]
Thanks, @Liaoshihua.  It's very good that you are being proactive.  Are you working with Ken Dockser on this?

**Comment by Liaoshihua** [comment]
@kdockser ，would you mind including riscv-bfloat16 in development partner management?
I want to provide gcc and binutils support for riscv-bfloat16.

**Comment by Liaoshihua** [comment]
In last two weeks，there has been no progress on this project and it is still under development. 
@jjscheel

**Comment by jjscheel** [comment]
@Liaoshihua, I'm working with Ken Dockser and Barna Ibrahim (Rivos PM) to clarify where the gaps are in this plan.  Once that's understood, we can write the SOW here.

THANKS for bringing this to my attention.

**Comment by jjscheel** [comment]
BTW, I'm setting this back to New until we can write the SOW and review it.

**Comment by jjscheel** [comment]
No update at this time.  Still awaiting feedback from the project manager working on this project.

**Comment by jjscheel** [comment]
@barna-rivos, any outlook for when gaps in this plan might be understood?  Thanks!

**Comment by jjscheel** [comment]
Any outlook for when we might understand the needs here better, @barna-rivos?

**Comment by jjscheel** [comment]
Hello, @Liaoshihua.  I've heard from Rivos that the work is underway and no DevPartner assistance is needed.  If you think that there may be pieces missing, please let me know and we can confirm the work will be done.

**Comment by Liaoshihua** [comment]
OK，let's close this issue
