### ISSUE TITLE
Bitmanip and Scalar Crypto Intrinsics in GCC

### ISSUE THREAD

**Issue by pz9115** [riscv-admin/dev-partners#37]
### Technical Group

Crypto TG

### ratification-pkg

Scalar Crypto & Bitmanip extensions

### Technical Liaison

Jiawei@iscas.ac.cn

### Task Category

Compilers/Toolchain

### Task Sub Category

- [X] gcc
- [ ] binutils
- [ ] gdb
- [X] intrinsics
- [ ] Java
- [ ] KVM
- [ ] ld
- [ ] llvm
- [ ] Linux kernel
- [ ] QEMU
- [ ] Spike

### Ratification Target

2021

### Statement of Work (SOW)

**Component names:**  gcc

**Requirements:**
  https://github.com/riscv-non-isa/riscv-c-api-doc/pull/44 merged

**Deliverables:**
  - gcc patches

**Acceptance Criteria:**
  - gcc support Bitmanip and Scalar Crypto extension intrinsic format in GCC upstream

**Projected timeframe:**
 - Supports Bitmanip intrinsics in gcc within Nov 2023
 - Supports Scalar Crypto intrinsics in gcc within Dec 2023

**SOW Signoffs:** 
  - Task group liaison sign-off
  - Development partner sign-off
  - Toolchains & Runtimes sign-off (if gcc, LLVM, binutils, gdb work)

### Waiver

- [ ] Freeze
- [ ] Ratification

### Pull Request Details

https://github.com/riscv-non-isa/riscv-c-api-doc/pull/44 finished review in the last week,
Now we are preparing to support this new feature in gcc upstream.

**Comment by cmuellner** [comment]
@pz9115, thank you very much for picking this up!

**Comment by jjscheel** [comment]
IYes, @pz9115, thank you!!!

A couple questions to consider as you plan this work:

1. What size is this (S, M, ...)?  See the field values for month estimates.
2. By what date do target having PR(s) accepted upstream?

I'm sure I'll have more questions, but these would be good to understand first.

**Comment by pz9115** [comment]
Still WIP, plan to send patches within this month.

**Comment by pz9115** [comment]
Sent the Scalar Crypto intrinsic implement to GCC upstream, Bitmanip part is still debugging, plan to send patch within this week.

https://gcc.gnu.org/pipermail/gcc-patches/2023-November/638238.html

**Comment by pz9115** [comment]
WIP, Shihua is updating the patch following Christoph's comments.

**Comment by pz9115** [comment]
Shihua resents his third version patches and waits for a new cycle review.

https://gcc.gnu.org/pipermail/gcc-patches/2023-December/641432.html

**Comment by pz9115** [comment]
Merged into upstream:

https://gcc.gnu.org/git?p=gcc.git;a=commit;h=c7ad6bf5b9e478d87294230318db675d7c8f3ce4

**Comment by jjscheel** [comment]
Thanks, Jiawei.  Does this mean that all work for this SOW is complete?

**Comment by pz9115** [comment]
Yes, it does. We can close this issue :)

**Comment by cmuellner** [comment]
Yes, I am happy to confirm that bitmanip and scalar crypto intrinsics are specified and available in LLVM and GCC.
To all involved people: thank you very much (especially Craig and @pz9115).

**Comment by jjscheel** [comment]
Complete.  Nice work, @pz9115!!!  Thanks for your help @cmuellner!
